# Makefile.in generated by automake 1.11.6 from Makefile.am.
# utils/qv4l2/Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011 Free Software
# Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




am__make_dryrun = \
  { \
    am__dry=no; \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        echo 'am--echo: ; @echo "AM"  OK' | $(MAKE) -f - 2>/dev/null \
          | grep '^AM OK$$' >/dev/null || am__dry=yes;; \
      *) \
        for am__flg in $$MAKEFLAGS; do \
          case $$am__flg in \
            *=*|--*) ;; \
            *n*) am__dry=yes; break;; \
          esac; \
        done;; \
    esac; \
    test $$am__dry = yes; \
  }
pkgdatadir = $(datadir)/v4l-utils
pkgincludedir = $(includedir)/v4l-utils
pkglibdir = $(libdir)/v4l-utils
pkglibexecdir = $(libexecdir)/v4l-utils
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = i686-pc-linux-gnu
host_triplet = i686-pc-linux-gnu
bin_PROGRAMS = qv4l2$(EXEEXT)
subdir = utils/qv4l2
DIST_COMMON = $(srcdir)/Makefile.am $(srcdir)/Makefile.in
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/m4/ac_define_dir.m4 \
	$(top_srcdir)/m4/gettext.m4 $(top_srcdir)/m4/iconv.m4 \
	$(top_srcdir)/m4/intlmacosx.m4 $(top_srcdir)/m4/lib-ld.m4 \
	$(top_srcdir)/m4/lib-link.m4 $(top_srcdir)/m4/lib-prefix.m4 \
	$(top_srcdir)/m4/libtool.m4 $(top_srcdir)/m4/ltoptions.m4 \
	$(top_srcdir)/m4/ltsugar.m4 $(top_srcdir)/m4/ltversion.m4 \
	$(top_srcdir)/m4/lt~obsolete.m4 $(top_srcdir)/m4/mode_t.m4 \
	$(top_srcdir)/m4/nls.m4 $(top_srcdir)/m4/po.m4 \
	$(top_srcdir)/m4/progtest.m4 $(top_srcdir)/m4/visibility.m4 \
	$(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = $(top_builddir)/config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)"
PROGRAMS = $(bin_PROGRAMS)
am_qv4l2_OBJECTS = qv4l2-qv4l2.$(OBJEXT) qv4l2-general-tab.$(OBJEXT) \
	qv4l2-ctrl-tab.$(OBJEXT) qv4l2-vbi-tab.$(OBJEXT) \
	qv4l2-v4l2-api.$(OBJEXT) qv4l2-capture-win.$(OBJEXT) \
	qv4l2-raw2sliced.$(OBJEXT)
nodist_qv4l2_OBJECTS = qv4l2-moc_qv4l2.$(OBJEXT) \
	qv4l2-moc_general-tab.$(OBJEXT) \
	qv4l2-moc_capture-win.$(OBJEXT) qv4l2-moc_vbi-tab.$(OBJEXT) \
	qv4l2-qrc_qv4l2.$(OBJEXT)
qv4l2_OBJECTS = $(am_qv4l2_OBJECTS) $(nodist_qv4l2_OBJECTS)
qv4l2_DEPENDENCIES = ../../lib/libv4l2/libv4l2.la \
	../../lib/libv4lconvert/libv4lconvert.la \
	../libv4l2util/libv4l2util.la
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
qv4l2_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CXXLD) $(AM_CXXFLAGS) \
	$(CXXFLAGS) $(qv4l2_LDFLAGS) $(LDFLAGS) -o $@
DEFAULT_INCLUDES = -I. -I$(top_builddir)
depcomp = $(SHELL) $(top_srcdir)/build-aux/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
LTCXXCOMPILE = $(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CXXFLAGS) $(CXXFLAGS)
AM_V_CXX = $(am__v_CXX_$(V))
am__v_CXX_ = $(am__v_CXX_$(AM_DEFAULT_VERBOSITY))
am__v_CXX_0 = @echo "  CXX   " $@;
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
CXXLD = $(CXX)
CXXLINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CXXLD) $(AM_CXXFLAGS) \
	$(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CXXLD = $(am__v_CXXLD_$(V))
am__v_CXXLD_ = $(am__v_CXXLD_$(AM_DEFAULT_VERBOSITY))
am__v_CXXLD_0 = @echo "  CXXLD " $@;
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC    " $@;
CCLD = $(CC)
LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD  " $@;
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN   " $@;
SOURCES = $(qv4l2_SOURCES) $(nodist_qv4l2_SOURCES)
DIST_SOURCES = $(qv4l2_SOURCES)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
ACLOCAL = ${SHELL} /home/out/Загрузки/v4l-utils-0.9.1/build-aux/missing --run aclocal-1.11
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 0
AR = ar
ARGP_LIBS = 
AUTOCONF = ${SHELL} /home/out/Загрузки/v4l-utils-0.9.1/build-aux/missing --run autoconf
AUTOHEADER = ${SHELL} /home/out/Загрузки/v4l-utils-0.9.1/build-aux/missing --run autoheader
AUTOMAKE = ${SHELL} /home/out/Загрузки/v4l-utils-0.9.1/build-aux/missing --run automake-1.11
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CFLAG_VISIBILITY = -fvisibility=hidden
CPP = gcc -E
CPPFLAGS = -I$(top_srcdir)/lib/include -Wall -Wpointer-arith -D_GNU_SOURCE -I$(top_srcdir)/include 
CXX = g++
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DLLTOOL = false
DLOPEN_LIBS = -ldl
DSYMUTIL = 
DUMPBIN = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
ENFORCE_LIBDVBV5_STATIC = 
ENFORCE_LIBV4L_STATIC = 
EXEEXT = 
FGREP = /bin/grep -F
GETTEXT_MACRO_VERSION = 0.17
GMSGFMT = /usr/bin/msgfmt
GMSGFMT_015 = /usr/bin/msgfmt
GREP = /bin/grep
HAVE_VISIBILITY = 1
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
INTLLIBS = 
INTL_MACOSX_LIBS = 
IR_KEYTABLE_SYSTEM_DIR = /lib/udev/rc_keymaps
IR_KEYTABLE_USER_DIR = /usr/local/etc/rc_keymaps
JPEG_LIBS = -ljpeg
LD = /usr/bin/ld
LDFLAGS = 
LIBICONV = 
LIBINTL = 
LIBOBJS = 
LIBS = 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIBV4L1_PRIV_DIR = /usr/local/lib/libv4l
LIBV4L2_PLUGIN_DIR = /usr/local/lib/libv4l/plugins
LIBV4L2_PRIV_DIR = /usr/local/lib/libv4l
LIBV4LCONVERT_PRIV_DIR = /usr/local/lib/libv4l
LIPO = 
LN_S = ln -s
LTLIBICONV = 
LTLIBINTL = 
LTLIBOBJS = 
MAINT = #
MAKEINFO = ${SHELL} /home/out/Загрузки/v4l-utils-0.9.1/build-aux/missing --run makeinfo
MANIFEST_TOOL = :
MKDIR_P = /bin/mkdir -p
MOC = /usr/lib/i386-linux-gnu/qt4/bin/moc
MSGFMT = /usr/bin/msgfmt
MSGFMT_015 = /usr/bin/msgfmt
MSGMERGE = /usr/bin/msgmerge
NM = /usr/bin/nm -B
NMEDIT = 
OBJDUMP = objdump
OBJEXT = o
OTOOL = 
OTOOL64 = 
PACKAGE = v4l-utils
PACKAGE_BUGREPORT = 
PACKAGE_NAME = v4l-utils
PACKAGE_STRING = v4l-utils 0.9.1
PACKAGE_TARNAME = v4l-utils
PACKAGE_URL = 
PACKAGE_VERSION = 0.9.1
PATH_SEPARATOR = :
PKG_CONFIG = /usr/bin/pkg-config
PKG_CONFIG_LIBDIR = 
PKG_CONFIG_PATH = 
POSUB = po
QT_CFLAGS = -DQT_SHARED -I/usr/include/qt4 -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I/usr/include/qt4/QtCore
QT_LIBS = -lQtGui -lQtCore
RANLIB = ranlib
SED = /bin/sed
SET_MAKE = 
SHELL = /bin/bash
STRIP = strip
UIC = /usr/lib/i386-linux-gnu/qt4/bin/uic
USE_NLS = yes
VERSION = 0.9.1
X11_CFLAGS = 
X11_LIBS = -lX11
XGETTEXT = /usr/bin/xgettext
XGETTEXT_015 = /usr/bin/xgettext
XGETTEXT_EXTRA_OPTIONS = 
abs_builddir = /home/out/Загрузки/v4l-utils-0.9.1/utils/qv4l2
abs_srcdir = /home/out/Загрузки/v4l-utils-0.9.1/utils/qv4l2
abs_top_builddir = /home/out/Загрузки/v4l-utils-0.9.1
abs_top_srcdir = /home/out/Загрузки/v4l-utils-0.9.1
ac_ct_AR = ar
ac_ct_CC = gcc
ac_ct_CXX = g++
ac_ct_DUMPBIN = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build = i686-pc-linux-gnu
build_alias = 
build_cpu = i686
build_os = linux-gnu
build_vendor = pc
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = i686-pc-linux-gnu
host_alias = 
host_cpu = i686
host_os = linux-gnu
host_vendor = pc
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/out/Загрузки/v4l-utils-0.9.1/build-aux/install-sh
keytablesystemdir = /lib/udev/rc_keymaps
keytableuserdir = ${prefix}/etc/rc_keymaps
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
libv4l1privdir = ${exec_prefix}/lib/libv4l
libv4l1subdir = libv4l
libv4l2plugindir = ${exec_prefix}/lib/libv4l/plugins
libv4l2privdir = ${exec_prefix}/lib/libv4l
libv4l2subdir = libv4l
libv4lconvertprivdir = ${exec_prefix}/lib/libv4l
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
pkgconfigdir = ${exec_prefix}/lib/pkgconfig
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = ../../
top_builddir = ../..
top_srcdir = ../..
udevrulesdir = /lib/udev/rules.d
qv4l2_SOURCES = qv4l2.cpp general-tab.cpp ctrl-tab.cpp vbi-tab.cpp v4l2-api.cpp capture-win.cpp \
  raw2sliced.cpp qv4l2.h capture-win.h general-tab.h vbi-tab.h v4l2-api.h raw2sliced.h

nodist_qv4l2_SOURCES = moc_qv4l2.cpp moc_general-tab.cpp moc_capture-win.cpp moc_vbi-tab.cpp qrc_qv4l2.cpp
qv4l2_LDADD = ../../lib/libv4l2/libv4l2.la ../../lib/libv4lconvert/libv4lconvert.la ../libv4l2util/libv4l2util.la
qv4l2_CPPFLAGS = $(QT_CFLAGS)
qv4l2_LDFLAGS = $(QT_LIBS)
EXTRA_DIST = exit.png fileopen.png qv4l2_24x24.png qv4l2_64x64.png qv4l2.png qv4l2.svg snapshot.png \
  video-television.png fileclose.png qv4l2_16x16.png qv4l2_32x32.png qv4l2.desktop qv4l2.qrc record.png \
  saveraw.png qv4l2.pro

all: all-am

.SUFFIXES:
.SUFFIXES: .cpp .lo .o .obj
$(srcdir)/Makefile.in: # $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      ( cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh ) \
	        && { if test -f $@; then exit 0; else break; fi; }; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu utils/qv4l2/Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --gnu utils/qv4l2/Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh

$(top_srcdir)/configure: # $(am__configure_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(ACLOCAL_M4): # $(am__aclocal_m4_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(am__aclocal_m4_deps):
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p || test -f $$p1; \
	  then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	    echo " $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	    $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' `; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	@list='$(bin_PROGRAMS)'; test -n "$$list" || exit 0; \
	echo " rm -f" $$list; \
	rm -f $$list || exit $$?; \
	test -n "$(EXEEXT)" || exit 0; \
	list=`for p in $$list; do echo "$$p"; done | sed 's/$(EXEEXT)$$//'`; \
	echo " rm -f" $$list; \
	rm -f $$list
qv4l2$(EXEEXT): $(qv4l2_OBJECTS) $(qv4l2_DEPENDENCIES) $(EXTRA_qv4l2_DEPENDENCIES) 
	@rm -f qv4l2$(EXEEXT)
	$(AM_V_CXXLD)$(qv4l2_LINK) $(qv4l2_OBJECTS) $(qv4l2_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/qv4l2-capture-win.Po
include ./$(DEPDIR)/qv4l2-ctrl-tab.Po
include ./$(DEPDIR)/qv4l2-general-tab.Po
include ./$(DEPDIR)/qv4l2-moc_capture-win.Po
include ./$(DEPDIR)/qv4l2-moc_general-tab.Po
include ./$(DEPDIR)/qv4l2-moc_qv4l2.Po
include ./$(DEPDIR)/qv4l2-moc_vbi-tab.Po
include ./$(DEPDIR)/qv4l2-qrc_qv4l2.Po
include ./$(DEPDIR)/qv4l2-qv4l2.Po
include ./$(DEPDIR)/qv4l2-raw2sliced.Po
include ./$(DEPDIR)/qv4l2-v4l2-api.Po
include ./$(DEPDIR)/qv4l2-vbi-tab.Po

.cpp.o:
	$(AM_V_CXX)$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ $<

.cpp.obj:
	$(AM_V_CXX)$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.cpp.lo:
	$(AM_V_CXX)$(LTCXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Plo
#	$(AM_V_CXX)source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LTCXXCOMPILE) -c -o $@ $<

qv4l2-qv4l2.o: qv4l2.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT qv4l2-qv4l2.o -MD -MP -MF $(DEPDIR)/qv4l2-qv4l2.Tpo -c -o qv4l2-qv4l2.o `test -f 'qv4l2.cpp' || echo '$(srcdir)/'`qv4l2.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/qv4l2-qv4l2.Tpo $(DEPDIR)/qv4l2-qv4l2.Po
#	$(AM_V_CXX)source='qv4l2.cpp' object='qv4l2-qv4l2.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o qv4l2-qv4l2.o `test -f 'qv4l2.cpp' || echo '$(srcdir)/'`qv4l2.cpp

qv4l2-qv4l2.obj: qv4l2.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT qv4l2-qv4l2.obj -MD -MP -MF $(DEPDIR)/qv4l2-qv4l2.Tpo -c -o qv4l2-qv4l2.obj `if test -f 'qv4l2.cpp'; then $(CYGPATH_W) 'qv4l2.cpp'; else $(CYGPATH_W) '$(srcdir)/qv4l2.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/qv4l2-qv4l2.Tpo $(DEPDIR)/qv4l2-qv4l2.Po
#	$(AM_V_CXX)source='qv4l2.cpp' object='qv4l2-qv4l2.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o qv4l2-qv4l2.obj `if test -f 'qv4l2.cpp'; then $(CYGPATH_W) 'qv4l2.cpp'; else $(CYGPATH_W) '$(srcdir)/qv4l2.cpp'; fi`

qv4l2-general-tab.o: general-tab.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT qv4l2-general-tab.o -MD -MP -MF $(DEPDIR)/qv4l2-general-tab.Tpo -c -o qv4l2-general-tab.o `test -f 'general-tab.cpp' || echo '$(srcdir)/'`general-tab.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/qv4l2-general-tab.Tpo $(DEPDIR)/qv4l2-general-tab.Po
#	$(AM_V_CXX)source='general-tab.cpp' object='qv4l2-general-tab.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o qv4l2-general-tab.o `test -f 'general-tab.cpp' || echo '$(srcdir)/'`general-tab.cpp

qv4l2-general-tab.obj: general-tab.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT qv4l2-general-tab.obj -MD -MP -MF $(DEPDIR)/qv4l2-general-tab.Tpo -c -o qv4l2-general-tab.obj `if test -f 'general-tab.cpp'; then $(CYGPATH_W) 'general-tab.cpp'; else $(CYGPATH_W) '$(srcdir)/general-tab.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/qv4l2-general-tab.Tpo $(DEPDIR)/qv4l2-general-tab.Po
#	$(AM_V_CXX)source='general-tab.cpp' object='qv4l2-general-tab.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o qv4l2-general-tab.obj `if test -f 'general-tab.cpp'; then $(CYGPATH_W) 'general-tab.cpp'; else $(CYGPATH_W) '$(srcdir)/general-tab.cpp'; fi`

qv4l2-ctrl-tab.o: ctrl-tab.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT qv4l2-ctrl-tab.o -MD -MP -MF $(DEPDIR)/qv4l2-ctrl-tab.Tpo -c -o qv4l2-ctrl-tab.o `test -f 'ctrl-tab.cpp' || echo '$(srcdir)/'`ctrl-tab.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/qv4l2-ctrl-tab.Tpo $(DEPDIR)/qv4l2-ctrl-tab.Po
#	$(AM_V_CXX)source='ctrl-tab.cpp' object='qv4l2-ctrl-tab.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o qv4l2-ctrl-tab.o `test -f 'ctrl-tab.cpp' || echo '$(srcdir)/'`ctrl-tab.cpp

qv4l2-ctrl-tab.obj: ctrl-tab.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT qv4l2-ctrl-tab.obj -MD -MP -MF $(DEPDIR)/qv4l2-ctrl-tab.Tpo -c -o qv4l2-ctrl-tab.obj `if test -f 'ctrl-tab.cpp'; then $(CYGPATH_W) 'ctrl-tab.cpp'; else $(CYGPATH_W) '$(srcdir)/ctrl-tab.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/qv4l2-ctrl-tab.Tpo $(DEPDIR)/qv4l2-ctrl-tab.Po
#	$(AM_V_CXX)source='ctrl-tab.cpp' object='qv4l2-ctrl-tab.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o qv4l2-ctrl-tab.obj `if test -f 'ctrl-tab.cpp'; then $(CYGPATH_W) 'ctrl-tab.cpp'; else $(CYGPATH_W) '$(srcdir)/ctrl-tab.cpp'; fi`

qv4l2-vbi-tab.o: vbi-tab.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT qv4l2-vbi-tab.o -MD -MP -MF $(DEPDIR)/qv4l2-vbi-tab.Tpo -c -o qv4l2-vbi-tab.o `test -f 'vbi-tab.cpp' || echo '$(srcdir)/'`vbi-tab.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/qv4l2-vbi-tab.Tpo $(DEPDIR)/qv4l2-vbi-tab.Po
#	$(AM_V_CXX)source='vbi-tab.cpp' object='qv4l2-vbi-tab.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o qv4l2-vbi-tab.o `test -f 'vbi-tab.cpp' || echo '$(srcdir)/'`vbi-tab.cpp

qv4l2-vbi-tab.obj: vbi-tab.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT qv4l2-vbi-tab.obj -MD -MP -MF $(DEPDIR)/qv4l2-vbi-tab.Tpo -c -o qv4l2-vbi-tab.obj `if test -f 'vbi-tab.cpp'; then $(CYGPATH_W) 'vbi-tab.cpp'; else $(CYGPATH_W) '$(srcdir)/vbi-tab.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/qv4l2-vbi-tab.Tpo $(DEPDIR)/qv4l2-vbi-tab.Po
#	$(AM_V_CXX)source='vbi-tab.cpp' object='qv4l2-vbi-tab.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o qv4l2-vbi-tab.obj `if test -f 'vbi-tab.cpp'; then $(CYGPATH_W) 'vbi-tab.cpp'; else $(CYGPATH_W) '$(srcdir)/vbi-tab.cpp'; fi`

qv4l2-v4l2-api.o: v4l2-api.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT qv4l2-v4l2-api.o -MD -MP -MF $(DEPDIR)/qv4l2-v4l2-api.Tpo -c -o qv4l2-v4l2-api.o `test -f 'v4l2-api.cpp' || echo '$(srcdir)/'`v4l2-api.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/qv4l2-v4l2-api.Tpo $(DEPDIR)/qv4l2-v4l2-api.Po
#	$(AM_V_CXX)source='v4l2-api.cpp' object='qv4l2-v4l2-api.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o qv4l2-v4l2-api.o `test -f 'v4l2-api.cpp' || echo '$(srcdir)/'`v4l2-api.cpp

qv4l2-v4l2-api.obj: v4l2-api.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT qv4l2-v4l2-api.obj -MD -MP -MF $(DEPDIR)/qv4l2-v4l2-api.Tpo -c -o qv4l2-v4l2-api.obj `if test -f 'v4l2-api.cpp'; then $(CYGPATH_W) 'v4l2-api.cpp'; else $(CYGPATH_W) '$(srcdir)/v4l2-api.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/qv4l2-v4l2-api.Tpo $(DEPDIR)/qv4l2-v4l2-api.Po
#	$(AM_V_CXX)source='v4l2-api.cpp' object='qv4l2-v4l2-api.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o qv4l2-v4l2-api.obj `if test -f 'v4l2-api.cpp'; then $(CYGPATH_W) 'v4l2-api.cpp'; else $(CYGPATH_W) '$(srcdir)/v4l2-api.cpp'; fi`

qv4l2-capture-win.o: capture-win.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT qv4l2-capture-win.o -MD -MP -MF $(DEPDIR)/qv4l2-capture-win.Tpo -c -o qv4l2-capture-win.o `test -f 'capture-win.cpp' || echo '$(srcdir)/'`capture-win.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/qv4l2-capture-win.Tpo $(DEPDIR)/qv4l2-capture-win.Po
#	$(AM_V_CXX)source='capture-win.cpp' object='qv4l2-capture-win.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o qv4l2-capture-win.o `test -f 'capture-win.cpp' || echo '$(srcdir)/'`capture-win.cpp

qv4l2-capture-win.obj: capture-win.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT qv4l2-capture-win.obj -MD -MP -MF $(DEPDIR)/qv4l2-capture-win.Tpo -c -o qv4l2-capture-win.obj `if test -f 'capture-win.cpp'; then $(CYGPATH_W) 'capture-win.cpp'; else $(CYGPATH_W) '$(srcdir)/capture-win.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/qv4l2-capture-win.Tpo $(DEPDIR)/qv4l2-capture-win.Po
#	$(AM_V_CXX)source='capture-win.cpp' object='qv4l2-capture-win.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o qv4l2-capture-win.obj `if test -f 'capture-win.cpp'; then $(CYGPATH_W) 'capture-win.cpp'; else $(CYGPATH_W) '$(srcdir)/capture-win.cpp'; fi`

qv4l2-raw2sliced.o: raw2sliced.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT qv4l2-raw2sliced.o -MD -MP -MF $(DEPDIR)/qv4l2-raw2sliced.Tpo -c -o qv4l2-raw2sliced.o `test -f 'raw2sliced.cpp' || echo '$(srcdir)/'`raw2sliced.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/qv4l2-raw2sliced.Tpo $(DEPDIR)/qv4l2-raw2sliced.Po
#	$(AM_V_CXX)source='raw2sliced.cpp' object='qv4l2-raw2sliced.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o qv4l2-raw2sliced.o `test -f 'raw2sliced.cpp' || echo '$(srcdir)/'`raw2sliced.cpp

qv4l2-raw2sliced.obj: raw2sliced.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT qv4l2-raw2sliced.obj -MD -MP -MF $(DEPDIR)/qv4l2-raw2sliced.Tpo -c -o qv4l2-raw2sliced.obj `if test -f 'raw2sliced.cpp'; then $(CYGPATH_W) 'raw2sliced.cpp'; else $(CYGPATH_W) '$(srcdir)/raw2sliced.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/qv4l2-raw2sliced.Tpo $(DEPDIR)/qv4l2-raw2sliced.Po
#	$(AM_V_CXX)source='raw2sliced.cpp' object='qv4l2-raw2sliced.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o qv4l2-raw2sliced.obj `if test -f 'raw2sliced.cpp'; then $(CYGPATH_W) 'raw2sliced.cpp'; else $(CYGPATH_W) '$(srcdir)/raw2sliced.cpp'; fi`

qv4l2-moc_qv4l2.o: moc_qv4l2.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT qv4l2-moc_qv4l2.o -MD -MP -MF $(DEPDIR)/qv4l2-moc_qv4l2.Tpo -c -o qv4l2-moc_qv4l2.o `test -f 'moc_qv4l2.cpp' || echo '$(srcdir)/'`moc_qv4l2.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/qv4l2-moc_qv4l2.Tpo $(DEPDIR)/qv4l2-moc_qv4l2.Po
#	$(AM_V_CXX)source='moc_qv4l2.cpp' object='qv4l2-moc_qv4l2.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o qv4l2-moc_qv4l2.o `test -f 'moc_qv4l2.cpp' || echo '$(srcdir)/'`moc_qv4l2.cpp

qv4l2-moc_qv4l2.obj: moc_qv4l2.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT qv4l2-moc_qv4l2.obj -MD -MP -MF $(DEPDIR)/qv4l2-moc_qv4l2.Tpo -c -o qv4l2-moc_qv4l2.obj `if test -f 'moc_qv4l2.cpp'; then $(CYGPATH_W) 'moc_qv4l2.cpp'; else $(CYGPATH_W) '$(srcdir)/moc_qv4l2.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/qv4l2-moc_qv4l2.Tpo $(DEPDIR)/qv4l2-moc_qv4l2.Po
#	$(AM_V_CXX)source='moc_qv4l2.cpp' object='qv4l2-moc_qv4l2.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o qv4l2-moc_qv4l2.obj `if test -f 'moc_qv4l2.cpp'; then $(CYGPATH_W) 'moc_qv4l2.cpp'; else $(CYGPATH_W) '$(srcdir)/moc_qv4l2.cpp'; fi`

qv4l2-moc_general-tab.o: moc_general-tab.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT qv4l2-moc_general-tab.o -MD -MP -MF $(DEPDIR)/qv4l2-moc_general-tab.Tpo -c -o qv4l2-moc_general-tab.o `test -f 'moc_general-tab.cpp' || echo '$(srcdir)/'`moc_general-tab.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/qv4l2-moc_general-tab.Tpo $(DEPDIR)/qv4l2-moc_general-tab.Po
#	$(AM_V_CXX)source='moc_general-tab.cpp' object='qv4l2-moc_general-tab.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o qv4l2-moc_general-tab.o `test -f 'moc_general-tab.cpp' || echo '$(srcdir)/'`moc_general-tab.cpp

qv4l2-moc_general-tab.obj: moc_general-tab.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT qv4l2-moc_general-tab.obj -MD -MP -MF $(DEPDIR)/qv4l2-moc_general-tab.Tpo -c -o qv4l2-moc_general-tab.obj `if test -f 'moc_general-tab.cpp'; then $(CYGPATH_W) 'moc_general-tab.cpp'; else $(CYGPATH_W) '$(srcdir)/moc_general-tab.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/qv4l2-moc_general-tab.Tpo $(DEPDIR)/qv4l2-moc_general-tab.Po
#	$(AM_V_CXX)source='moc_general-tab.cpp' object='qv4l2-moc_general-tab.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o qv4l2-moc_general-tab.obj `if test -f 'moc_general-tab.cpp'; then $(CYGPATH_W) 'moc_general-tab.cpp'; else $(CYGPATH_W) '$(srcdir)/moc_general-tab.cpp'; fi`

qv4l2-moc_capture-win.o: moc_capture-win.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT qv4l2-moc_capture-win.o -MD -MP -MF $(DEPDIR)/qv4l2-moc_capture-win.Tpo -c -o qv4l2-moc_capture-win.o `test -f 'moc_capture-win.cpp' || echo '$(srcdir)/'`moc_capture-win.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/qv4l2-moc_capture-win.Tpo $(DEPDIR)/qv4l2-moc_capture-win.Po
#	$(AM_V_CXX)source='moc_capture-win.cpp' object='qv4l2-moc_capture-win.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o qv4l2-moc_capture-win.o `test -f 'moc_capture-win.cpp' || echo '$(srcdir)/'`moc_capture-win.cpp

qv4l2-moc_capture-win.obj: moc_capture-win.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT qv4l2-moc_capture-win.obj -MD -MP -MF $(DEPDIR)/qv4l2-moc_capture-win.Tpo -c -o qv4l2-moc_capture-win.obj `if test -f 'moc_capture-win.cpp'; then $(CYGPATH_W) 'moc_capture-win.cpp'; else $(CYGPATH_W) '$(srcdir)/moc_capture-win.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/qv4l2-moc_capture-win.Tpo $(DEPDIR)/qv4l2-moc_capture-win.Po
#	$(AM_V_CXX)source='moc_capture-win.cpp' object='qv4l2-moc_capture-win.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o qv4l2-moc_capture-win.obj `if test -f 'moc_capture-win.cpp'; then $(CYGPATH_W) 'moc_capture-win.cpp'; else $(CYGPATH_W) '$(srcdir)/moc_capture-win.cpp'; fi`

qv4l2-moc_vbi-tab.o: moc_vbi-tab.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT qv4l2-moc_vbi-tab.o -MD -MP -MF $(DEPDIR)/qv4l2-moc_vbi-tab.Tpo -c -o qv4l2-moc_vbi-tab.o `test -f 'moc_vbi-tab.cpp' || echo '$(srcdir)/'`moc_vbi-tab.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/qv4l2-moc_vbi-tab.Tpo $(DEPDIR)/qv4l2-moc_vbi-tab.Po
#	$(AM_V_CXX)source='moc_vbi-tab.cpp' object='qv4l2-moc_vbi-tab.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o qv4l2-moc_vbi-tab.o `test -f 'moc_vbi-tab.cpp' || echo '$(srcdir)/'`moc_vbi-tab.cpp

qv4l2-moc_vbi-tab.obj: moc_vbi-tab.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT qv4l2-moc_vbi-tab.obj -MD -MP -MF $(DEPDIR)/qv4l2-moc_vbi-tab.Tpo -c -o qv4l2-moc_vbi-tab.obj `if test -f 'moc_vbi-tab.cpp'; then $(CYGPATH_W) 'moc_vbi-tab.cpp'; else $(CYGPATH_W) '$(srcdir)/moc_vbi-tab.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/qv4l2-moc_vbi-tab.Tpo $(DEPDIR)/qv4l2-moc_vbi-tab.Po
#	$(AM_V_CXX)source='moc_vbi-tab.cpp' object='qv4l2-moc_vbi-tab.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o qv4l2-moc_vbi-tab.obj `if test -f 'moc_vbi-tab.cpp'; then $(CYGPATH_W) 'moc_vbi-tab.cpp'; else $(CYGPATH_W) '$(srcdir)/moc_vbi-tab.cpp'; fi`

qv4l2-qrc_qv4l2.o: qrc_qv4l2.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT qv4l2-qrc_qv4l2.o -MD -MP -MF $(DEPDIR)/qv4l2-qrc_qv4l2.Tpo -c -o qv4l2-qrc_qv4l2.o `test -f 'qrc_qv4l2.cpp' || echo '$(srcdir)/'`qrc_qv4l2.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/qv4l2-qrc_qv4l2.Tpo $(DEPDIR)/qv4l2-qrc_qv4l2.Po
#	$(AM_V_CXX)source='qrc_qv4l2.cpp' object='qv4l2-qrc_qv4l2.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o qv4l2-qrc_qv4l2.o `test -f 'qrc_qv4l2.cpp' || echo '$(srcdir)/'`qrc_qv4l2.cpp

qv4l2-qrc_qv4l2.obj: qrc_qv4l2.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT qv4l2-qrc_qv4l2.obj -MD -MP -MF $(DEPDIR)/qv4l2-qrc_qv4l2.Tpo -c -o qv4l2-qrc_qv4l2.obj `if test -f 'qrc_qv4l2.cpp'; then $(CYGPATH_W) 'qrc_qv4l2.cpp'; else $(CYGPATH_W) '$(srcdir)/qrc_qv4l2.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/qv4l2-qrc_qv4l2.Tpo $(DEPDIR)/qv4l2-qrc_qv4l2.Po
#	$(AM_V_CXX)source='qrc_qv4l2.cpp' object='qv4l2-qrc_qv4l2.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(qv4l2_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o qv4l2-qrc_qv4l2.obj `if test -f 'qrc_qv4l2.cpp'; then $(CYGPATH_W) 'qrc_qv4l2.cpp'; else $(CYGPATH_W) '$(srcdir)/qrc_qv4l2.cpp'; fi`

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS)
installdirs:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic clean-libtool clean-local \
	mostlyclean-am

distclean: distclean-am
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am: install-data-local

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS

.MAKE: install-am install-strip

.PHONY: CTAGS GTAGS all all-am check check-am clean clean-binPROGRAMS \
	clean-generic clean-libtool clean-local ctags distclean \
	distclean-compile distclean-generic distclean-libtool \
	distclean-tags distdir dvi dvi-am html html-am info info-am \
	install install-am install-binPROGRAMS install-data \
	install-data-am install-data-local install-dvi install-dvi-am \
	install-exec install-exec-am install-html install-html-am \
	install-info install-info-am install-man install-pdf \
	install-pdf-am install-ps install-ps-am install-strip \
	installcheck installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic mostlyclean-libtool pdf pdf-am ps ps-am \
	tags uninstall uninstall-am uninstall-binPROGRAMS


clean-local:
	-rm -vf moc_*.cpp qrc_*.cpp qrc_*.o ui_*.h

# Call the moc preprocessor
moc_qv4l2.cpp: $(srcdir)/qv4l2.h
	$(MOC) -o $@ $(srcdir)/qv4l2.h

moc_general-tab.cpp: $(srcdir)/general-tab.h
	$(MOC) -o $@ $(srcdir)/general-tab.h

moc_vbi-tab.cpp: $(srcdir)/vbi-tab.h
	$(MOC) -o $@ $(srcdir)/vbi-tab.h

moc_capture-win.cpp: $(srcdir)/capture-win.h
	$(MOC) -o $@ $(srcdir)/capture-win.h

# Call the Qt resource compiler
qrc_qv4l2.cpp: $(srcdir)/qv4l2.qrc
	rcc -name qv4l2 -o $@ $(srcdir)/qv4l2.qrc

install-data-local:
	$(INSTALL_DATA) -D -p "$(srcdir)/qv4l2.desktop"   "$(DESTDIR)$(datadir)/applications/qv4l2.desktop"
	$(INSTALL_DATA) -D -p "$(srcdir)/qv4l2_16x16.png" "$(DESTDIR)$(datadir)/icons/hicolor/16x16/apps/qv4l2.png"
	$(INSTALL_DATA) -D -p "$(srcdir)/qv4l2_24x24.png" "$(DESTDIR)$(datadir)/icons/hicolor/24x24/apps/qv4l2.png"
	$(INSTALL_DATA) -D -p "$(srcdir)/qv4l2_32x32.png" "$(DESTDIR)$(datadir)/icons/hicolor/32x32/apps/qv4l2.png"
	$(INSTALL_DATA) -D -p "$(srcdir)/qv4l2_64x64.png" "$(DESTDIR)$(datadir)/icons/hicolor/64x64/apps/qv4l2.png"
	$(INSTALL_DATA) -D -p "$(srcdir)/qv4l2.svg"       "$(DESTDIR)$(datadir)/icons/hicolor/scalable/apps/qv4l2.svg"

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
